# **Python Code Practice** (Basic 140+)

42 code solutions, with additional concepts and notes

## Lambda Function

A lambda function in Python is a small, anonymous function defined with the `lambda` keyword. It can have any number of input parameters but only one expression. Lambda functions are often used for short, throwaway functions that are used only once or for simple operations.

### Syntax

The syntax of a lambda function is:

```python
lambda arguments: expression
```

### Characteristics

1. **Anonymous**: Lambda functions do not have a name. They are often used where function objects are required.
2. **Single Expression**: They contain a single expression, which is evaluated and returned. This makes them less versatile than regular functions, but also concise and convenient for simple operations.

### Example Usages

1. **Basic Lambda Function**:
    ```python
    add = lambda x, y: x + y
    print(add(2, 3))  # Output: 5
    ```

2. **Using Lambda in Higher-Order Functions**:
    Lambda functions are often used with higher-order functions like `map()`, `filter()`, and `sorted()`.

    - **`map()` Example**:
        ```python
        numbers = [1, 2, 3, 4]
        squared = map(lambda x: x**2, numbers)
        print(list(squared))  # Output: [1, 4, 9, 16]
        ```

    - **`filter()` Example**:
        ```python
        numbers = [1, 2, 3, 4]
        evens = filter(lambda x: x % 2 == 0, numbers)
        print(list(evens))  # Output: [2, 4]
        ```

    - **`sorted()` Example**:
        ```python
        items = [{'name': 'apple', 'price': 10}, {'name': 'banana', 'price': 5}]
        sorted_items = sorted(items, key=lambda x: x['price'])
        print(sorted_items)
        # Output: [{'name': 'banana', 'price': 5}, {'name': 'apple', 'price': 10}]
        ```

3. **Immediate Use**:
    Lambda functions can be defined and used immediately.

    ```python
    print((lambda x, y: x * y)(3, 4))  # Output: 12
    ```

### Advantages

- **Concise**: Useful for small, simple operations, making the code more readable.
- **Inline Definition**: Can be defined inline where they are needed, reducing the need for standalone function definitions.

### Limitations

- **Single Expression**: Limited to a single expression, which restricts their functionality compared to regular functions.
- **Readability**: Overuse or complex lambda functions can make code harder to read and understand.

### Example of Sorting Using Lambda

As shown in the previous example of sorting a dictionary by values, lambda functions can be particularly handy:

```python
example_dict = {'a': 3, 'b': 1, 'c': 2, 'd': 5, 'e': 4}
sorted_dict = dict(sorted(example_dict.items(), key=lambda item: item[1]))
print(sorted_dict)  # Output: {'b': 1, 'c': 2, 'a': 3, 'e': 4, 'd': 5}
```

In this example, the `lambda` function `lambda item: item[1]` is used to extract the value part of each key-value pair for sorting.

Lambda functions are a powerful feature in Python, especially for concise, throwaway functions used in higher-order functions and for simple expressions.

## Zip

The `zip` function in Python is used to combine multiple lists (or other iterable objects) element-wise into tuples. It creates an iterator that aggregates elements from each of the iterables. The resulting iterator can be used to create a list of tuples, where each tuple contains one element from each of the input iterables at the same position.

### Basic Syntax

```python
zip(iterable1, iterable2, ...)
```

### Simple Explanation

1. **Combine Elements**:
    - `zip` takes multiple iterables (e.g., lists, tuples) and combines their elements based on their positions.
    - The first elements of each iterable are paired together, the second elements are paired together, and so on.

2. **Result as Tuples**:
    - The combined elements are returned as tuples. Each tuple contains one element from each iterable.

### Example Usage

```python
# Two lists to be zipped together
list1 = [1, 2, 3]
list2 = ['a', 'b', 'c']

# Using zip to combine the lists
zipped = zip(list1, list2)

# Converting the zip object to a list to see the result
zipped_list = list(zipped)
print(zipped_list)  # Output: [(1, 'a'), (2, 'b'), (3, 'c')]
```

### Explanation of the Example

1. **Input Lists**:
    - `list1 = [1, 2, 3]`
    - `list2 = ['a', 'b', 'c']`

2. **Using `zip`**:
    - `zip(list1, list2)` pairs the first element of `list1` with the first element of `list2`, the second element of `list1` with the second element of `list2`, and so on.

3. **Result**:
    - The resulting pairs are tuples: `[(1, 'a'), (2, 'b'), (3, 'c')]`.

### Handling Different Lengths

If the input iterables are of different lengths, `zip` stops creating pairs when the shortest input iterable is exhausted.

```python
list1 = [1, 2, 3]
list2 = ['a', 'b']

zipped = zip(list1, list2)
zipped_list = list(zipped)
print(zipped_list)  # Output: [(1, 'a'), (2, 'b')]
```

In this case, since `list2` is shorter, the resulting list only contains pairs for the first two elements.

### Unzipping

You can also "unzip" a zipped object back into individual lists using the `zip` function with the unpacking operator `*`.

```python
zipped_list = [(1, 'a'), (2, 'b'), (3, 'c')]
unzipped = list(zip(*zipped_list))
print(unzipped)  # Output: [(1, 2, 3), ('a', 'b', 'c')]
```

### Summary

- **Combine Elements**: The `zip` function pairs elements from multiple iterables based on their positions.
- **Result as Tuples**: The paired elements are returned as tuples.
- **Different Lengths**: If the iterables have different lengths, `zip` stops at the end of the shortest one.
- **Unzipping**: You can unzip a zipped object back into individual lists.

The `zip` function is a convenient way to combine elements from multiple iterables and is widely used in Python programming for tasks like iterating over multiple lists in parallel.

### **Program 24**
Write a Python Program to Convert Decimal to Binary, Octal and Hexadecimal.

In [1]:
dec_num = int(input('Enter a decimal number: '))
print(f"The decimal value of dec_num is: {dec_num}")
print(bin(dec_num),"in binary.")
print(oct(dec_num),"in octal.")
print(hex(dec_num),"in hexadecimal.")

Enter a decimal number: 10
The decimal value of dec_num is: 10
0b1010 in binary.
0o12 in octal.
0xa in hexadecimal.


### **Program 26**
Write a Python Program to Make a Simple Calculator with 4 basic mathematicaloperations.

In [2]:
print("please select your math operation: addition, subtraction, multiplication, division ")

opip = input()

print("please enter the operands")

num1 = int(input())
num2 = int(input())

if opip == "addition" :
  res = num1 + num2
elif opip == "subtraction":
  res = num1 - num2
elif opip == "multiplication":
  res = num1 * num2
elif opip == "division" & num2 != 0:
  res = num1 / num2
else:
  print('please type a valid operation name')

print(f"Result = ", res)

please select your math operation: addition, subtraction, multiplication, division 
addition
please enter the operands
2
2
Result =  4


### **Program 27**
Write a Python Program to Display Fibonacci Sequence Using Recursion.

Fibonacci sequence:
The Fibonacci sequence is a series of numbers in which each number is the sum of the two preceding ones, usually starting with 0 and 1. In mathematical terms, it is defined by the recurrence relation ( F(n) = F(n-1) + F(n-2) ), with initial conditions ( F(0) = 0 ) and ( F(1) = 1). The sequence begins: 0, 1, 1, 2, 3, 5, 8, 13, 21, and so on.

In [3]:
# Python program to display the Fibonacci sequence

def recur_fibo(n):
  if n <= 1:
    return n
  else:
    return(recur_fibo(n-1)+recur_fibo(n-2))

nterms = int(input("Enter the number of terms(greater than zero): "))

#check if the number of terms is valid
if nterms <= 0:
  print("Please enter a positove integer")
else:
  print("Fibonacci sequence")
  for i in range(nterms):
    print(recur_fibo(i))


Enter the number of terms(greater than zero): 5
Fibonacci sequence
0
1
1
2
3


### **Program 28**
Write a Python Program to Find Factorial of Number Using Recursion.

The factorial of a non-negative integer ( n ) is the product of all positive integers less than orequal to ( n ).

In [4]:
def recur_factorial (n):
  if n <= 2:
    return n
  else:
    return n*recur_factorial(n-1)

num =int(input("Enter the number: "))

# check if the number is negative

if num < 0:
  print("Sorry, factorial does not exist for negative numbers")
elif num == 0 :
  print("The factorial of 0 is 1")
else:
  print("The factorial of",num,"is",recur_factorial(num))

Enter the number: 5
The factorial of 5 is 120


### **Program 34**
Write a Python Program for array rotation.

In [5]:
# function to rotate array by d elements using temp array
def rotateArray(arr, n, d):
    temp = []
    i = 0
    while (i < d):
        temp.append(arr[i])
        i = i + 1
    i = 0
    while (d < n):
        arr[i] = arr[d]
        i = i + 1
        d = d + 1
    arr[:] = arr[: i] + temp
    return arr


# Driver function to test above function
arr = [1, 2, 3, 4, 5, 6, 7]
print("Array after left rotation is: ", end=' ')
print(rotateArray(arr, len(arr), 2))

Array after left rotation is:  [3, 4, 5, 6, 7, 1, 2]


### **Program 37**
Write a Python Program to Add Two Matrices.

https://www.programiz.com/python-programming/examples/add-matrix

In [6]:
# Program to add two matrices using nested loop

X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

# iterate through rows
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[0])):
       result[i][j] = X[i][j] + Y[i][j]

for r in result:
   print(r)


[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


### **Program 38**
Write a Python Program to Multiply Two Matrices.

https://www.programiz.com/python-programming/examples/multiply-matrix
https://www.youtube.com/watch?v=l6Ol6qYeFaQ&ab_channel=ProgrammingForBeginners

In [7]:
# Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]

for r in result:
   print(r)


[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


### **Program 39**
Write a Python Program to Transpose a Matrix.

In [8]:
# Program to transpose a matrix using a nested loop

X = [[12,7],
    [4 ,5],
    [3 ,8]]

result = [[0,0,0],
         [0,0,0]]

# iterate through rows
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[0])):
       result[j][i] = X[i][j]

for r in result:
   print(r)


[12, 4, 3]
[7, 5, 8]


### **Program 45**
Write a Python program to check if the given number is Happy Number.

From Wikipedia, the free encyclopaedia:
A happy number is defined by the following process:
Starting with any positive integer, replace the number by the sum of the squares of its digits, and repeat the process until the number equals 1 (where it will stay), or it loops endlessly in a cycle which does not include 1. Those numbers for which this process ends in 1 are happy numbers, while those that do not end in 1 are unhappy numbers.


This code is for checking if a number is a "happy number" or not. Here's a simple explanation:

1. It defines a function called `is_happy_number` that takes one argument, `num`.

2. It initializes an empty set called `seen`, which will be used to store numbers that have been encountered during the process.

3. The code enters a loop that continues until either `num` becomes 1 (indicating it's a happy number) or `num` is found in the `seen` set (indicating it's not a happy number).

4. Inside the loop, it adds the current `num` to the `seen` set.

5. It calculates the next `num` by summing the squares of each digit of the current `num`. This is done by converting `num` to a string, iterating over its digits, converting each digit back to an integer, squaring it, and then summing them up.

6. After the loop, it returns `True` if `num` is equal to 1 (indicating it's a happy number), and `False` otherwise.

So, in simple terms, the function checks whether a given number is a happy number or not, where a happy number is defined as a number that eventually reaches 1 when the process described above is repeated, and an unhappy number is one that gets stuck in a cycle and never reaches 1.

https://www.w3resource.com/python-exercises/basic/python-basic-1-exercise-66.php

Explanation:

Here is a breakdown of the above Python code:

Define a function named "is_Happy_num()" that takes a number 'n' as input.
Initialize a set called 'past' to keep track of previously encountered numbers during the process.
Use a while loop to continue the process until the number becomes 1 (a Happy Number) or a cycle is detected.
Inside the loop, calculate the sum of the squares of each digit in the current number.
Check if the current number has been encountered before. If yes, it forms a cycle, and the number is not a Happy Number.
Add the current number to the set of past numbers.
Return 'True' if the process reaches 1, indicating that the number is a Happy Number.
Test the function with different inputs to check its functionality.

In [9]:
# Function to check if a number is a Happy Number
def is_Happy_num(n):
    past = set()  # Set to store previously encountered numbers during the process
    while n != 1:  # Continue the process until the number becomes 1 (a Happy Number) or a cycle is detected
        n = sum(int(i) ** 2 for i in str(n))  # Calculate the sum of squares of each digit in the number
        if n in past:  # If the current number has been encountered before, it forms a cycle
            return False  # The number is not a Happy Number
        past.add(n)  # Add the current number to the set of past numbers
    return True  # If the process reaches 1, the number is a Happy Number

# Test cases
print(is_Happy_num(7))
print(is_Happy_num(932))
print(is_Happy_num(6))


True
True
False


### **Program 48**
Write a Python program to print all pronic numbers between 1 and 100

A pronic number, also known as an oblong number or rectangular number, is a type offigurate number that represents a rectangle. It is the product of two consecutive integers, nand (n + 1). Mathematically, a pronic number can be expressed as:

In [10]:
def is_pronic(num):
    """
    Function to check if a number is pronic.
    """
    for i in range(num):
        if i * (i + 1) == num:
            return True
    return False

def print_pronic_numbers():
    """
    Function to print all pronic numbers between 1 and 100.
    """
    pronic_numbers = []
    for num in range(1, 101):
        if is_pronic(num):
            pronic_numbers.append(num)
    print("Pronic numbers between 1 and 100:")
    print(pronic_numbers)

print_pronic_numbers()

Pronic numbers between 1 and 100:
[2, 6, 12, 20, 30, 42, 56, 72, 90]


This program defines two functions:

1. `is_pronic(num)`: This function checks if a given number `num` is pronic by iterating through all numbers less than `num` and checking if their product is equal to `num`. If such a pair is found, the function returns `True`, otherwise `False`.

2. `print_pronic_numbers()`: This function prints all pronic numbers between 1 and 100 by iterating through the numbers in that range and checking if each number is pronic using the `is_pronic()` function. It collects all pronic numbers in a list and then prints that list.

When you run this program, it will output all the pronic numbers between 1 and 100.

In [11]:
def is_pronic_number(num):
  for n in range(1, int(num**0.5) + 1):
     if n * (n + 1) == num:
        return True
  return False

print("Pronic numbers between 1 and 100 are:")
for i in range(1, 101):
     if is_pronic_number(i):
           print(i, end=" | ")


Pronic numbers between 1 and 100 are:
2 | 6 | 12 | 20 | 30 | 42 | 56 | 72 | 90 | 

This code defines a function `is_pronic_number(num)` that checks whether a given number is a pronic number. A pronic number is a number that is the product of two consecutive integers.

Here's how the code works:

1. The function `is_pronic_number(num)` takes a number `num` as input.

2. It then iterates over a range of numbers from 1 to the square root of `num` plus 1.

3. Within this loop, it checks if the product of the current number `n` and the next consecutive number `(n + 1)` is equal to `num`. If it is, the function returns `True`, indicating that `num` is a pronic number.

4. If no such pair is found after the loop, the function returns `False`, indicating that `num` is not a pronic number.

5. The code then prints the pronic numbers between 1 and 100 by iterating over a range from 1 to 100 and printing each number if it is a pronic number according to the `is_pronic_number()` function.

When you run this code, it will print all the pronic numbers between 1 and 100.

Q: Why does it iterate over a range of numbers from 1 to the square root of num plus 1?

The code iterates over a range of numbers from 1 to the square root of `num` plus 1 because it's sufficient to check for pairs of consecutive integers up to the square root of `num` to determine if `num` is a pronic number.

Here's why:

1. A pronic number is the product of two consecutive integers. If one of those integers is greater than the square root of the pronic number, then the other integer must be less than the square root in order for their product to equal the pronic number.

2. By checking for pairs of consecutive integers up to the square root of `num`, the code efficiently covers all possible pairs of consecutive integers that could multiply to give `num`.

3. Once the loop reaches the square root of `num`, checking for pairs of consecutive integers becomes redundant because any remaining pairs would have already been covered. So, there's no need to continue the loop beyond the square root of `num`.

Therefore, iterating over a range from 1 to the square root of `num` plus 1 ensures that the code checks all possible pairs of consecutive integers efficiently, making it a practical approach to determine if `num` is a pronic number.

### **Program 61**
Write a Python program for removing
character from a string.

In [12]:
def remove_ith_character(s, i):
    """
    This function removes the character at index i from the string s.

    :param s: The original string
    :param i: The index of the character to remove
    :return: The string with the ith character removed
    """
    if i < 0 or i >= len(s):
        return "Index out of range"

    # Using string slicing to remove the ith character
    return s[:i] + s[i+1:]

# Example usage
original_string = "Hello, World!"
index_to_remove = 7

result = remove_ith_character(original_string, index_to_remove)
print(f"Original string: {original_string}")
print(f"String after removing {index_to_remove}th character: {result}")

Original string: Hello, World!
String after removing 7th character: Hello, orld!


### **Program 63**
Write a Python program to check if a given string is binary string or not.

In [13]:
def is_binary_string(s):
    """
    This function checks if the given string s is a binary string (contains only '0' and '1').

    :param s: The string to check
    :return: True if the string is binary, False otherwise
    """
    for char in s:
        if char not in '01':
            return False
    return True

# Example usage
test_string1 = "101010"
test_string2 = "102010"
test_string3 = "abcde"

print(f"Is '{test_string1}' a binary string? {is_binary_string(test_string1)}")
print(f"Is '{test_string2}' a binary string? {is_binary_string(test_string2)}")
print(f"Is '{test_string3}' a binary string? {is_binary_string(test_string3)}")


Is '101010' a binary string? True
Is '102010' a binary string? False
Is 'abcde' a binary string? False


Explanation:

1. **Function Definition**:
    - The function `is_binary_string` takes one parameter, `s`, which is the string to check.

2. **Loop Through Characters**:
    - The function iterates through each character in the string `s`.

3. **Check Characters**:
    - It checks if each character is either '0' or '1'. If any character is not '0' or '1', the function returns `False`.

4. **Return True**:
    - If all characters in the string are '0' or '1', the function returns `True`.

Example Usage:

- **test_string1** is "101010", which is a binary string.
- **test_string2** is "102010", which is not a binary string because it contains '2'.
- **test_string3** is "abcde", which is not a binary string because it contains letters.

When you run the program, the output will be:

```
Is '101010' a binary string? True
Is '102010' a binary string? False
Is 'abcde' a binary string? False
```

This checks each string and correctly identifies whether it is a binary string or not.

### **Program 65**
Write a Python program to find all duplicate characters in string.


In [17]:
def find_duplicate_characters(s):
    """
    This function finds and returns all duplicate characters in the string s.

    :param s: The string to check
    :return: A list of duplicate characters
    """
    # Create an empty dictionary to store character counts
    char_count = {}
   # Initialize a list to store duplicate characters
    duplicates = []

    # Count the occurrences of each character
    for char in s:
        if char in char_count:
            # If the character is already in the dictionary, increment
            char_count[char] += 1
        else:
            char_count[char] = 1

    # Find characters that appear more than once
    for char, count in char_count.items():
        if count > 1:
            duplicates.append(char)

    return duplicates

# Example usage
test_string = "programming"

result = find_duplicate_characters(test_string)
print(f"Duplicate characters in '{test_string}' are: {result}")


Duplicate characters in 'programming' are: ['r', 'g', 'm']


Explanation:

1. **Function Definition**:
    - The function `find_duplicate_characters` takes one parameter, `s`, which is the string to check.

2. **Counting Characters**:
    - A dictionary `char_count` is used to count the occurrences of each character in the string.
    - The for loop iterates over each character in the string `s`. If the character is already in `char_count`, it increments the count. If not, it adds the character to `char_count` with a count of 1.

3. **Finding Duplicates**:
    - The function then iterates over the items in the `char_count` dictionary. If a character's count is greater than 1, it means the character is a duplicate, and it is added to the `duplicates` list.

4. **Return Statement**:
    - The function returns the list of duplicate characters.

Example Usage:

- **test_string** is "programming".

When you run the program, the output will be:

```
Duplicate characters in 'programming' are: ['r', 'g', 'm']
```

This output shows that the characters 'r', 'g', and 'm' appear more than once in the string "programming".

### **Program 67**
Write a Python program to Extract Unique dictionary values.

In [18]:
#To extract unique values from a dictionary, you can use a set to collect the unique values.

def extract_unique_values(input_dict):
    """
    This function extracts unique values from the given dictionary.

    :param input_dict: The dictionary to extract values from
    :return: A set of unique values
    """

    # Initialize an empty set to store unique values
    unique_values = set()

    # Iterate through the values of the dictionary
    for value in input_dict.values():
        if isinstance(value, list):
            unique_values.update(value)
        else:
            unique_values.add(value)

    return unique_values

# Example usage
example_dict = {
    'a': 1,
    'b': 2,
    'c': 3,
    'd': 2,
    'e': 4,
    'f': 3,
    'g': [1, 2, 3],
    'h': [2, 4, 6]
}

result = extract_unique_values(example_dict)
print(f"Unique values in the dictionary: {result}")


Unique values in the dictionary: {1, 2, 3, 4, 6}


Explanation:

1. **Function Definition**:
    - The function `extract_unique_values` takes one parameter, `input_dict`, which is the dictionary to extract unique values from.

2. **Set for Unique Values**:
    - A set `unique_values` is used to store unique values because sets automatically handle duplicate values.

3. **Iterating over Dictionary Values**:
    - The function iterates over all values in the dictionary using `input_dict.values()`.
    - If a value is a list, the function uses `update` to add all elements of the list to the set. If it's a single value, it uses `add` to add the value to the set.

4. **Return Statement**:
    - The function returns the set of unique values.

Example Usage:

- **example_dict** contains a mix of single values and lists as values.

When you run the program, the output will be:

```
Unique values in the dictionary: {1, 2, 3, 4, 6}
```

This output shows the unique values extracted from the dictionary, including all unique elements from the lists within the dictionary.

### **Program 70**
Write a Python program to convert key-values list to flat dictionary.

In [19]:
def list_to_flat_dict(key_value_list):
    """
    This function converts a list of key-value pairs into a flat dictionary.

    :param key_value_list: A list of tuples, where each tuple contains a key-value pair
    :return: A dictionary containing the key-value pairs
    """

    # Initialize an empty dictionary
    flat_dict = {}

    # Iterate through the list and add key-value pairs to the dictionary
    for key, value in key_value_list:
        flat_dict[key] = value

    return flat_dict

# Example usage
key_value_list = [('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5)]

result = list_to_flat_dict(key_value_list)
print("Flat dictionary:", result)


Flat dictionary: {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}


Explanation:

1. **Function Definition**:
    - The function `list_to_flat_dict` takes one parameter, `key_value_list`, which is a list of tuples. Each tuple contains a key-value pair.

2. **Creating the Dictionary**:
    - An empty dictionary `flat_dict` is initialized.
    - The function iterates over each key-value pair in the `key_value_list` and assigns the value to the corresponding key in the dictionary.

3. **Return Statement**:
    - The function returns the `flat_dict` which now contains all the key-value pairs from the list.

Example Usage:

- **key_value_list** is a list of tuples, where each tuple contains a key and a value.

When you run the program, the output will be:

```
Flat dictionary: {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
```

This output shows that the list of key-value pairs has been successfully converted into a flat dictionary.

### **Program 72**
Write a Python program to check order of character in string using OrderedDict().

In [20]:
from collections import OrderedDict

def check_order(string,reference):
   # Create OrderedDicts for both strings
   string_dict=OrderedDict.fromkeys(string)
   reference_dict= OrderedDict.fromkeys(reference)
   #Check if the OrderedDict for the string matches the OrderedDict
   return string_dict==reference_dict

# Input strings
input_string = "hello world"
reference_string = "helo wrd"

# Check if the order of characters in input_string matches reference_st
if check_order (input_string,reference_string):
  print ("The order of characters in the input string matches the reference string.")
else:
  print( "The order of characters in the input string does not match the reference string.")

The order of characters in the input string matches the reference string.


To check the order of characters in a string using OrderedDict means to verify whether a specified sequence of characters (pattern) appears in the same order in the given string. The OrderedDict from the collections module maintains the order in which keys are inserted, making it suitable for this task.

### **Program 73**
Write a Python program to sort Python Dictionaries by Key or Value.

In [21]:
def sort_dict_by_values(input_dict):
    """
    This function sorts a dictionary by its values.

    :param input_dict: The dictionary to sort
    :return: A sorted dictionary by values
    """
    # Using sorted() to sort the dictionary by values
    sorted_dict = dict(sorted(input_dict.items(), key=lambda item: item[1]))
    return sorted_dict

# Example usage
example_dict = {
    'a': 3,
    'b': 1,
    'c': 2,
    'd': 5,
    'e': 4
}

sorted_result = sort_dict_by_values(example_dict)
print("Original dictionary:", example_dict)
print("Sorted dictionary by values:", sorted_result)


Original dictionary: {'a': 3, 'b': 1, 'c': 2, 'd': 5, 'e': 4}
Sorted dictionary by values: {'b': 1, 'c': 2, 'a': 3, 'e': 4, 'd': 5}


Explanation:

1. **Function Definition**:
    - The function `sort_dict_by_values` takes one parameter, `input_dict`, which is the dictionary to be sorted.

2. **Sorting the Dictionary**:
    - The `sorted` function is used to sort the dictionary. The `input_dict.items()` method returns a view object that displays a list of a dictionary's key-value tuple pairs.
    - The `key` argument in the `sorted` function is a lambda function `lambda item: item[1]`, which indicates that sorting should be based on the dictionary values (`item[1]`).

3. **Convert to Dictionary**:
    - The `sorted` function returns a list of tuples sorted by the dictionary values. Using `dict()`, we convert this sorted list of tuples back into a dictionary.

4. **Return Statement**:
    - The function returns the sorted dictionary.

Example Usage:

- **example_dict** contains keys with integer values.

When you run the program, the output will be:

```
Original dictionary: {'a': 3, 'b': 1, 'c': 2, 'd': 5, 'e': 4}
Sorted dictionary by values: {'b': 1, 'c': 2, 'a': 3, 'e': 4, 'd': 5}
```

This output shows the original dictionary and the dictionary sorted by its values in ascending order. The keys 'b', 'c', 'a', 'e', and 'd' are now sorted according to their corresponding values 1, 2, 3, 4, and 5, respectively.

### **Program 74**
Write a program that calculates and prints the value according to the given formula:

Break down the code `print(','.join(map(str, result)))`
to understand what it does step by step.

Step-by-Step Explanation

1. **`map(str, result)`**:
    - The `map` function applies the `str` function to each element in the iterable `result`.
    - This converts each element in `result` to its string representation.
    - Example: If `result = [1, 2, 3]`, `map(str, result)` will produce `['1', '2', '3']`.

2. **`','.join(...)`**:
    - The `join` method is called on the string `','`.
    - It concatenates all the elements in the iterable (produced by `map(str, result)`) into a single string, with each element separated by a comma.
    - Example: `','.join(['1', '2', '3'])` will produce the string `'1,2,3'`.

3. **`print(...)`**:
    - The `print` function outputs the resulting string to the console.

Full Example

If we have `result = [1, 2, 3]`, the code `print(','.join(map(str, result)))` will:

1. Convert each number to a string: `['1', '2', '3']`
2. Join these strings with commas: `'1,2,3'`
3. Print the final string: `1,2,3`

Example with Code:

```python
result = [1, 2, 3]
print(','.join(map(str, result)))  # Output: 1,2,3
```

Detailed Breakdown:

1. **`result = [1, 2, 3]`**:
    - The list `result` contains the integers 1, 2, and 3.

2. **`map(str, result)`**:
    - `map` takes two arguments: a function and an iterable. It applies the function (`str` in this case) to each item in the iterable (`result`).
    - It produces an iterator of strings: `['1', '2', '3']`.

3. **`','.join(...)`**:
    - The `join` method concatenates these strings with a comma between each pair of elements.
    - It results in the string `'1,2,3'`.

4. **`print(...)`**:
    - The `print` function outputs the final string `'1,2,3'` to the console.

Why Use This Code?

This code is useful when you need to convert a list of items to a single string where items are separated by a specific delimiter (a comma in this case). This is often used in scenarios like creating CSV (Comma-Separated Values) strings, formatting output, or generating a string representation of a list for display purposes.

Another Example:

Let's consider another example where `result` is a list of words:

```python
result = ['apple', 'banana', 'cherry']
print(','.join(map(str, result)))  # Output: apple,banana,cherry
```

In this example:
1. `map(str, result)` is essentially unnecessary because `result` already contains strings.
2. `','.join(result)` directly joins the words with commas.
3. The `print` function outputs `apple,banana,cherry`.

This code effectively and concisely converts lists of elements into a neatly formatted string.

### **Program 75**
Write a program which takes 2 digits, X,Y as input and generates a 2-dimensionalarray. The element value in the i-th row and j-th column of the array should be i*j.

In [22]:
# Function to generate 2D array
def generate_2d_array(x, y):
    array = []
    for i in range(x):
        row = []
        for j in range(y):
            row.append(i * j)
        array.append(row)
    return array

# Input: Two digits X and Y
x = int(input("Enter the number of rows (X): "))
y = int(input("Enter the number of columns (Y): "))

# Generate the 2D array
result_array = generate_2d_array(x, y)

# Print the 2D array
for row in result_array:
    print(row)


Enter the number of rows (X): 2
Enter the number of columns (Y): 2
[0, 0]
[0, 1]


Explanation:

1. **Function Definition**:
    - The function `generate_2d_array(x, y)` creates a 2-dimensional array with `x` rows and `y` columns.
    - It initializes an empty list `array` to hold the rows.
    - It uses nested loops to iterate over the range of `x` (rows) and `y` (columns).
    - For each pair of indices `(i, j)`, it calculates the product `i * j` and appends it to the current row.
    - After constructing each row, it appends the row to the `array`.

2. **User Input**:
    - The program prompts the user to input the number of rows (`x`) and columns (`y`).

3. **Generate the 2D Array**:
    - The program calls the `generate_2d_array(x, y)` function with the user inputs and stores the result in `result_array`.

4. **Print the 2D Array**:
    - The program iterates over the rows of `result_array` and prints each row.

Example Usage:

```
Enter the number of rows (X): 3
Enter the number of columns (Y): 4
[0, 0, 0, 0]
[0, 1, 2, 3]
[0, 2, 4, 6]
```

In this example:
- The user inputs `3` for the number of rows and `4` for the number of columns.
- The program generates a 2-dimensional array with 3 rows and 4 columns.
- The value of each element in the array is the product of its row and column indices.

The resulting array is:
```
[
 [0, 0, 0, 0],
 [0, 1, 2, 3],
 [0, 2, 4, 6]
]
```

This program can be used to create any size of 2-dimensional array based on the given input dimensions.

### **Program 80**

A website requires the users to input username and password to register. Write aprogram to check the validity of password input by users. Following are the criteriafor checking the password:
1. At least 1 letter between [a-z]
2. At least 1 number between [0-9]
1. At least 1 letter between [A-Z]
3.
At least 1 character from [$#@]
4. Minimum length of transaction password: 6
5. Maximum length of transaction password: 12
Your program should accept a sequence of comma separated passwords and willcheck them according to the above criteria. Passwords that match the criteria are tobe printed, each separated by a comma.
Example
If the following passwords are given as input to the program:
ABd1234@1,a F1#,2w3E*,2We3345
Then, the output of the program should be:
ABd1234@1

In [23]:
import re

def is_valid_password(password):
    # Check the length of the password
    if len(password) < 6 or len(password) > 12:
        return False

    # Check for at least one lowercase letter
    if not re.search("[a-z]", password):
        return False

    # Check for at least one uppercase letter
    if not re.search("[A-Z]", password):
        return False

    # Check for at least one digit
    if not re.search("[0-9]", password):
        return False

    # Check for at least one special character from [$#@]
    if not re.search("[$#@]", password):
        return False

    return True

# Input: sequence of comma-separated passwords
passwords = input("Enter passwords, separated by commas: ").split(',')

# Filter valid passwords
valid_passwords = [pwd for pwd in passwords if is_valid_password(pwd)]

# Output valid passwords, separated by commas
print(",".join(valid_passwords))


Enter passwords, separated by commas: Hellooooo!



Certainly! Let's break down the regular expression pattern `r"^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[$#@])"` and explain how it works in the context of `re.match`.

## Regular Expression Breakdown

- `^`: This asserts the position at the start of the string. It ensures that the match starts from the beginning of the string.

- `(?=.*[a-z])`: This is a positive lookahead assertion. It means that there must be at least one lowercase letter (`[a-z]`) somewhere in the string. The `.*` before `[a-z]` allows for any number of any characters to appear before the lowercase letter.

- `(?=.*[A-Z])`: This is another positive lookahead assertion. It ensures that there is at least one uppercase letter (`[A-Z]`) somewhere in the string. Again, `.*` allows for any number of characters before the uppercase letter.

- `(?=.*[0-9])`: This positive lookahead assertion ensures that there is at least one digit (`[0-9]`) somewhere in the string.

- `(?=.*[$#@])`: This positive lookahead assertion ensures that there is at least one special character from the set `[$#@]` somewhere in the string.

### How It Works

When you use `re.match` with this pattern, it checks the entire string to see if all the conditions specified in the lookahead assertions are met.

Here's what happens step by step:

1. **`re.match(r"^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[$#@])", password)`**:
    - The `re.match` function attempts to match the given pattern to the string `password`.
    - The `^` at the beginning ensures that the match starts at the beginning of the string.

2. **Positive Lookaheads**:
    - `(?=.*[a-z])`: Checks if there's at least one lowercase letter in the string.
    - `(?=.*[A-Z])`: Checks if there's at least one uppercase letter in the string.
    - `(?=.*[0-9])`: Checks if there's at least one digit in the string.
    - `(?=.*[$#@])`: Checks if there's at least one special character (`$`, `#`, or `@`) in the string.

Each of these lookaheads is independent of the others. They do not consume characters in the string but assert that the required characters exist somewhere in the string.

### Example

Consider the password `ABd1234@1`:

- `(?=.*[a-z])`: The string contains the lowercase letter `d`.
- `(?=.*[A-Z])`: The string contains the uppercase letters `A` and `B`.
- `(?=.*[0-9])`: The string contains the digits `1`, `2`, `3`, and `4`.
- `(?=.*[$#@])`: The string contains the special character `@`.

Since `ABd1234@1` meets all these conditions, the `re.match` will succeed.

### Full Program Context

Here's how this would be used in a complete program to validate passwords:

```python
import re

def is_valid_password(password):
    # Check if password matches the required pattern
    pattern = r"^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[$#@])"
    if re.match(pattern, password) and 6 <= len(password) <= 12:
        return True
    return False

# Input: sequence of comma-separated passwords
passwords = input("Enter passwords, separated by commas: ").split(',')

# Filter valid passwords
valid_passwords = [pwd for pwd in passwords if is_valid_password(pwd)]

# Output valid passwords, separated by commas
print(",".join(valid_passwords))
```

### Summary

- The `re.match` function with the given regular expression pattern ensures that the password contains at least one lowercase letter, one uppercase letter, one digit, and one special character from the set `[$#@]`.
- The `.*` within each lookahead allows for any number of characters before the required character type.
- The full pattern `^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[$#@])` ensures that all conditions are checked without consuming any characters in the string.
- This pattern, combined with a length check, validates that a password meets the specified criteria.

QA Topic **YIELD**

In Python, the `yield` keyword is used in functions to turn them into generators. Generators are a special type of iterator that allow you to iterate over a sequence of values, but unlike normal functions, generators can yield values one at a time and resume where they left off when called again.

## How `yield` Works

When a function contains the `yield` keyword, it is transformed into a generator function. When called, the generator function returns a generator object without executing the function. When the generator's `__next__()` method is called (e.g., via the `next()` function or by iterating over it), the function executes until it reaches the `yield` keyword, which provides a value to the code that called `next()` and pauses the function's execution, saving its state. When `__next__()` is called again, the function resumes execution immediately after the `yield` statement.

### Example of a Generator Function

```python
def simple_generator():
    yield 1
    yield 2
    yield 3

# Creating a generator object
gen = simple_generator()

# Iterating over the generator
print(next(gen))  # Output: 1
print(next(gen))  # Output: 2
print(next(gen))  # Output: 3

# When the generator is exhausted, it raises StopIteration
# print(next(gen))  # Raises StopIteration
```

### Key Points

1. **State Retention**:
    - Unlike a regular function that exits when it returns a value, a generator function retains its state between yields. This allows it to resume execution where it left off.

2. **Lazy Evaluation**:
    - Generators produce items only when asked (lazy evaluation). This makes them very memory efficient, especially when dealing with large data sets or infinite sequences.

3. **Example with a Loop**:
    - Generators are often used with loops to produce a series of values.

```python
def count_up_to(max):
    count = 1
    while count <= max:
        yield count
        count += 1

# Using the generator
counter = count_up_to(5)
for num in counter:
    print(num)
# Output: 1 2 3 4 5
```

### Benefits of Using `yield`

1. **Memory Efficiency**:
    - Generators are memory efficient because they yield items one at a time and do not store the entire sequence in memory.

2. **Representing Infinite Sequences**:
    - Generators can represent infinite sequences, like the Fibonacci sequence or a sequence of prime numbers, without running into memory issues.

3. **Pipeline Processing**:
    - Generators can be used in pipelines, where data is processed in stages, each stage represented by a generator.

### Practical Example: Fibonacci Sequence

```python
def fibonacci_sequence():
    a, b = 0, 1
    while True:
        yield a
        a, b = b, a + b

# Using the generator
fib = fibonacci_sequence()
for _ in range(10):
    print(next(fib))
# Output: 0 1 1 2 3 5 8 13 21 34
```

In this example, the `fibonacci_sequence` generator produces the Fibonacci sequence indefinitely, one value at a time.

### Summary

- **`yield`**: Turns a function into a generator, allowing it to produce a series of values lazily.
- **State Retention**: The function retains its state between `yield` calls.
- **Memory Efficiency**: Generators are more memory-efficient than lists, especially for large or infinite sequences.
- **Lazy Evaluation**: Values are generated on-the-fly when needed, rather than all at once.

Using `yield` in Python is a powerful way to create iterators with less memory overhead and the ability to produce values on demand.

**Program 84**
Please write a program to generate all sentences where subject is in ["I", "You"] andverb is in ["Play", "Love"] and the object is in ["Hockey","Football"].

In [24]:
subjects=["I","You"]
verbs=["Play", "Love"]
objects=["Hockey","Football"]

sentences = []

for sub in subjects :
   for vrb in verbs :
      for obj in objects :
             sentence = f"{ sub } { vrb } { obj }."
             sentences.append(sentence)

for sentence in sentences :
   print (sentence)

I Play Hockey.
I Play Football.
I Love Hockey.
I Love Football.
You Play Hockey.
You Play Football.
You Love Hockey.
You Love Football.


### **Program 86**
Please write a binary search function which searches an item in a sorted list. Thefunction should return the index of element to be searched in the list.

In [25]:
def binary_search(arr, target):
    low = 0
    high = len(arr) - 1

    while low <= high:
        mid = (low + high) // 2

        # Check if target is present at mid
        if arr[mid] == target:
            return mid

        # If target is greater, ignore left half
        elif arr[mid] < target:
            low = mid + 1

        # If target is smaller, ignore right half
        else:
            high = mid - 1

    # If we reach here, the element was not present
    return -1

# Example usage:
sorted_list = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
target_element = 12

# Perform binary search
result_index = binary_search(sorted_list, target_element)

if result_index != -1:
    print(f"Element {target_element} found at index {result_index}.")
else:
    print(f"Element {target_element} not found in the list.")

Element 12 found at index 5.


Python function that implements binary search to find an item in a sorted list. Binary search is efficient for searching in sorted lists because it repeatedly divides the search interval in half until the target element is found or the interval is empty.

Explanation of the Binary Search Function:

1. **Initialization**:
   - `low` is set to the index of the first element (0) and `high` to the index of the last element (`len(arr) - 1`).

2. **Binary Search Loop**:
   - The loop continues until `low` is less than or equal to `high`.
   - `mid` is calculated as the middle index of the current search interval.
   
3. **Comparison**:
   - If the middle element (`arr[mid]`) is equal to `target`, return `mid` (index of the target).
   - If `arr[mid]` is less than `target`, adjust `low` to `mid + 1` to search in the right half of the list.
   - If `arr[mid]` is greater than `target`, adjust `high` to `mid - 1` to search in the left half of the list.
   
4. **End of Search**:
   - If the loop exits without finding the element (`low` > `high`), return `-1` indicating the element is not present in the list.

5. **Example Usage**:
   - In the example, `sorted_list` is a sorted list, and `target_element` is the element we are searching for (`12` in this case).
   - The function returns the index `5` for `12` because it's found at that position in `sorted_list`.

Key Points:

- **Efficiency**: Binary search runs in `O(log n)` time complexity, where `n` is the number of elements in the list, because it halves the search space at each step.
- **Precondition**: Binary search requires the list to be sorted for correct results.

### **Program 89**
The Fibonacci Sequence is computed based on the following formula:
f(n)=0 if n=0
f(n)=1 if n=1
f(n)=f(n-1)+f(n-2) if n>1
Please write a program using list comprehension to print the Fibonacci Sequence incomma separated form with a given n input by console.
Example:
If the following n is given as input to the program:
8
Then, the output of the program should be:
0,1,1,2,3,5,8,13

In [26]:
def fibonacci_sequence(n):
    # Initialize the first two terms of the sequence
    fib_sequence = [0, 1]

    # Generate the Fibonacci sequence using list comprehension
    [fib_sequence.append(fib_sequence[-1] + fib_sequence[-2]) for _ in range(2, n)]

    # Return the Fibonacci sequence
    return fib_sequence[:n]

# Input: n
n = int(input("Enter the number of terms for Fibonacci sequence: "))

# Generate Fibonacci sequence using list comprehension
fibonacci = fibonacci_sequence(n)

# Print the Fibonacci sequence in comma-separated form
print(",".join(map(str, fibonacci)))


Enter the number of terms for Fibonacci sequence: 5
0,1,1,2,3


Python program using list comprehension to generate and print the Fibonacci sequence up to the nth term provided by the user:



Explanation:

1. **`fibonacci_sequence` Function**:
   - `fibonacci_sequence(n)` generates the Fibonacci sequence up to `n` terms using list comprehension.
   - The sequence starts with `[0, 1]`.
   - It then iteratively appends the sum of the last two elements (`fib_sequence[-1] + fib_sequence[-2]`) to `fib_sequence` until the desired number of terms `n` is reached.

2. **List Comprehension**:
   - `[fib_sequence.append(fib_sequence[-1] + fib_sequence[-2]) for _ in range(2, n)]`:
     - This list comprehension is used to extend `fib_sequence` by computing the Fibonacci numbers beyond the initial `[0, 1]`.
     - `_` is a placeholder variable as it's common to use `_` when the variable itself is not needed in the loop.

3. **Input and Output**:
   - User inputs the number `n` which determines how many Fibonacci numbers are generated.
   - The Fibonacci sequence up to `n` terms is printed in a comma-separated format using `",".join(map(str, fibonacci))`.

Example Usage:

If the user inputs `8`, the program will output:
```
0,1,1,2,3,5,8,13
```

This corresponds to the Fibonacci sequence up to the 8th term, as specified.

Key Points:

- **Efficiency**: This approach uses list comprehension to efficiently generate the Fibonacci sequence in a concise manner.
- **Flexibility**: The program dynamically computes the sequence based on user input, allowing for different sequence lengths.

### **Program 91**
Define a class named Shape and its subclass Square. The Square class has an initfunction which takes a length as argument. Both classes have an area function whichcan print the area of the shape where Shape's area is 0 by default.

In [27]:
class Shape:
    def __init__(self):
        pass

    def area(self):
        return 0

class Square(Shape):
    def __init__(self, length):
        super().__init__()
        self.length = length

    def area(self):
        return self.length * self.length

# Example usage:
square = Square(5)
print("Area of square:", square.area())  # Output: 25

shape = Shape()
print("Area of shape:", shape.area())  # Output: 0


Area of square: 25
Area of shape: 0


define the `Shape` class and its subclass `Square` in Python, including their respective `area` methods:



Explanation:

1. **Shape Class**:
   - `Shape` is defined as a base class with an `__init__` method that doesn't do anything specific in this example.
   - It has an `area` method that returns `0` by default. This method can be overridden by subclasses to provide specific implementations.

2. **Square Class (Subclass of Shape)**:
   - `Square` inherits from `Shape` using `class Square(Shape):`.
   - It has an `__init__` method that takes a `length` parameter to initialize the side length of the square.
   - The `area` method is overridden to calculate the area of the square using the formula `length * length`.

3. **Example Usage**:
   - An instance `square` of `Square` is created with a side length of `5`.
   - Calling `square.area()` prints the area of the square, which is `25`.
   - An instance `shape` of `Shape` is also created, although `Shape` itself doesn't need any parameters for initialization.
   - Calling `shape.area()` prints the default area of `0` for a generic shape.

Key Points:

- **Inheritance**: `Square` inherits from `Shape`, allowing it to use and potentially override methods defined in `Shape`.
- **Method Override**: The `area` method is overridden in `Square` to provide a specific implementation for calculating the area of a square.
- **Default Behavior**: The `Shape` class provides a default `area` method that can be used by subclasses or overridden as needed.

This structure demonstrates basic class inheritance and method overriding in Python, allowing for flexibility and customization in defining shapes and their respective areas.

### **Program 101**
Create a function that computes the hamming distance between two strings.

The Hamming distance between two strings of equal length is the number of positions at which the corresponding symbols are different. Here's a Python function that computes the Hamming distance between two strings:

In [28]:
def hamming_distance(str1, str2):
    if len(str1) != len(str2):
        raise ValueError("Strings must be of the same length")

    return sum(el1 != el2 for el1, el2 in zip(str1, str2))

# Example usage:
str1 = "karolin"
str2 = "kathrin"
print(f"Hamming distance between '{str1}' and '{str2}': {hamming_distance(str1, str2)}")

str1 = "karolin"
str2 = "kerstin"
print(f"Hamming distance between '{str1}' and '{str2}': {hamming_distance(str1, str2)}")


Hamming distance between 'karolin' and 'kathrin': 3
Hamming distance between 'karolin' and 'kerstin': 3


Explanation:

1. **Length Check**:
   - The function first checks if the lengths of `str1` and `str2` are the same. If they are not, it raises a `ValueError` because Hamming distance is only defined for strings of equal length.

2. **Calculate Hamming Distance**:
   - `zip(str1, str2)` pairs up corresponding characters from `str1` and `str2`.
   - The generator expression `sum(el1 != el2 for el1, el2 in zip(str1, str2))` iterates over these pairs, comparing the characters. If the characters are different (`el1 != el2`), it returns `True` (which is equivalent to `1` when summed). If they are the same, it returns `False` (equivalent to `0` when summed).
   - The `sum` function adds up these `1`s and `0`s to give the total Hamming distance.

Example Usage:

- For the strings `"karolin"` and `"kathrin"`, the Hamming distance is `3` because the characters differ at three positions: the fourth, fifth, and sixth characters.
- For the strings `"karolin"` and `"kerstin"`, the Hamming distance is `3` because the characters differ at the third, fourth, and seventh positions.

This function efficiently calculates the Hamming distance and handles the error case where the strings are of different lengths.

### **Program 106**
Write a function that moves all elements of one type to the end of the list.

Below is a Python function that moves all elements of a specified type to the end of a list while preserving the order of the other elements:

```python
def move_elements_to_end(lst, element_type):
    # Separate elements of the specified type and the rest
    specified_elements = [element for element in lst if isinstance(element, element_type)]
    other_elements = [element for element in lst if not isinstance(element, element_type)]
    
    # Concatenate other elements followed by the specified elements
    return other_elements + specified_elements

# Example usage:
sample_list = [1, 'a', 2, 'b', 3, 'c', 4]
element_type = str
result = move_elements_to_end(sample_list, element_type)
print(result)  # Output: [1, 2, 3, 4, 'a', 'b', 'c']
```

Explanation:

1. **Separate Elements by Type**:
   - The list comprehension `[element for element in lst if isinstance(element, element_type)]` collects all elements of the specified type from the list.
   - The list comprehension `[element for element in lst if not isinstance(element, element_type)]` collects all elements that are not of the specified type.

2. **Concatenate Lists**:
   - `other_elements + specified_elements` concatenates the list of elements that are not of the specified type with the list of elements that are of the specified type.

3. **Return Result**:
   - The concatenated list is returned as the result.

Example Usage:

- `sample_list` is `[1, 'a', 2, 'b', 3, 'c', 4]`.
- `element_type` is `str`.
- The function moves all strings to the end, resulting in `[1, 2, 3, 4, 'a', 'b', 'c']`.

This approach ensures that the order of the non-specified elements is preserved, and all elements of the specified type are moved to the end of the list.

## Enumerate function

The `enumerate` function in Python is a built-in function that allows you to iterate over a list (or any iterable) and have access to both the index and the value of each element in the iterable. This is particularly useful when you need to modify elements in a list or when you simply need to know the position of each element.

Syntax

The basic syntax of `enumerate` is:
```python
enumerate(iterable, start=0)
```

- `iterable`: The sequence or collection you want to iterate over.
- `start`: The index value from which the counter is to start (default is 0).

How It Works

`enumerate` returns an enumerate object, which is an iterator. This object yields pairs of an index and an element from the iterable, which you can use in a for loop.

Example

Here’s a simple example to illustrate how `enumerate` works:

```python
fruits = ['apple', 'banana', 'cherry']

# Using enumerate in a for loop
for index, fruit in enumerate(fruits):
    print(f"Index {index}: {fruit}")
```

**Output:**
```
Index 0: apple
Index 1: banana
Index 2: cherry
```

Explanation:

1. **Iteration with Index**:
   - In the above example, `enumerate(fruits)` creates an iterator that generates pairs: `(0, 'apple')`, `(1, 'banana')`, `(2, 'cherry')`.
   - The `for` loop then unpacks these pairs into `index` and `fruit`, allowing you to access both the index and the value during each iteration.

2. **Custom Starting Index**:
   - You can specify a different starting index by passing a second argument to `enumerate`. For example:
     ```python
     for index, fruit in enumerate(fruits, start=1):
         print(f"Index {index}: {fruit}")
     ```
   - This will start counting from 1 instead of the default 0.

**Output:**
```
Index 1: apple
Index 2: banana
Index 3: cherry
```

Use Cases

- **When modifying a list in place**: If you need to update elements in a list based on their index, `enumerate` is very handy.
- **When creating enumerated outputs**: It’s useful for generating numbered lists, tracking positions, or debugging.

Overall, `enumerate` is a powerful and convenient tool for working with iterables in Python, especially when both the index and value are needed.

### **Program 113**
Given a list of numbers, create a function which returns the list but with eachelement's index in the list added to itself. This means you add 0 to the number atindex 0, add 1 to the number at index 1, etc...

To create a function that adds each element's index to itself in a list, you can use a combination of `enumerate` and list comprehension. The `enumerate` function provides both the index and the value as you iterate through the list, which makes it easy to add the index to the value.

Here's the implementation:

```python
def add_index_to_elements(numbers):
    # Using list comprehension with enumerate to add index to each element
    return [num + index for index, num in enumerate(numbers)]

# Example usage:
numbers = [10, 20, 30, 40, 50]
result = add_index_to_elements(numbers)
print(result)  # Output: [10, 21, 32, 43, 54]
```

Explanation:

1. **`enumerate(numbers)`**:
   - `enumerate` is a built-in Python function that adds a counter to an iterable. It returns an enumerate object, which yields pairs of index and value for each item in the list.

2. **List Comprehension**:
   - The list comprehension `[num + index for index, num in enumerate(numbers)]` iterates over each index and number in the list.
   - `index` is the position of the element in the list, and `num` is the element's value.
   - The expression `num + index` adds the index to the element's value.
   - The result of this operation for each element is collected into a new list, which is returned by the function.

3. **Example Usage**:
   - For the input list `[10, 20, 30, 40, 50]`, the function returns `[10, 21, 32, 43, 54]` because:
     - Index 0: `10 + 0 = 10`
     - Index 1: `20 + 1 = 21`
     - Index 2: `30 + 2 = 32`
     - Index 3: `40 + 3 = 43`
     - Index 4: `50 + 4 = 54`

This function efficiently adds the index to each element in the list, returning a new list with the modified values.

### **Program 115**
This Triangular Number Sequence is generated from a pattern of dots that form atriangle. The first 5 numbers of the sequence, or dots, are:
1, 3, 6, 10, 15
This means that the first triangle has just one dot, the second one has three dots, thethird one has 6 dots and so on.
Write a function that gives the number of dots with its corresponding triangle numberof the sequence.
Examples
triangle(1) ➞ 1
triangle(6) ➞ 21
triangle(215) ➞ 23220

The Triangular Number Sequence can be represented mathematically. The nth triangular number is the sum of the first \( n \) natural numbers, which can be calculated using the formula:

\[
T(n) = \frac{n \times (n + 1)}{2}
\]

where \( T(n) \) is the nth triangular number.

Here's a Python function that takes a triangle number \( n \) and returns the number of dots in that triangle:

```python
def triangular_number(n):
    return (n * (n + 1)) // 2

# Example usage:
n = 5
number_of_dots = triangular_number(n)
print(f"The {n}th triangular number has {number_of_dots} dots.")
```

Explanation:

1. **Triangular Number Formula**:
   - The formula \( \frac{n \times (n + 1)}{2} \) calculates the number of dots in the nth triangular number. This formula comes from the sum of the first \( n \) natural numbers.

2. **Function Definition**:
   - The function `triangular_number(n)` takes an integer \( n \) and computes the nth triangular number using the formula.

3. **Example Usage**:
   - For \( n = 5 \), the function calculates the 5th triangular number:
     \[
     T(5) = \frac{5 \times (5 + 1)}{2} = \frac{30}{2} = 15
     \]
   - Thus, the 5th triangular number has 15 dots.

The function `triangular_number` can be used to find the number of dots in any triangle number in the sequence by passing the desired \( n \) as an argument.

## '//'  in python

In Python, `//` is an operator used for **floor division**. It divides two numbers and returns the largest integer less than or equal to the quotient. This is different from regular division, which uses the `/` operator and returns a float.

Examples of Floor Division

1. **Basic Usage with Positive Numbers**:
   ```python
   result = 7 // 3
   print(result)  # Output: 2
   ```
   - Here, `7 / 3` would be `2.333...`, but `7 // 3` gives `2` because `2` is the largest integer less than or equal to `2.333...`.

2. **Floor Division with Negative Numbers**:
   ```python
   result = -7 // 3
   print(result)  # Output: -3
   ```
   - In this case, `-7 / 3` would be `-2.333...`, but `-7 // 3` gives `-3` because `-3` is the largest integer less than or equal to `-2.333...`.

3. **Using with Floating-Point Numbers**:
   ```python
   result = 7.5 // 2
   print(result)  # Output: 3.0
   ```
   - Here, `7.5 / 2` is `3.75`, and `7.5 // 2` returns `3.0`, which is the largest integer less than or equal to `3.75` in float format.

Why Use Floor Division?

- **Avoiding Floats**: If you only need the integer part of a division and want to avoid dealing with floating-point numbers, floor division is useful.
- **Efficiency**: It can be slightly more efficient in certain calculations where you need to ensure the result is an integer.

**Note**: Floor division always returns an integer type if both operands are integers, and a float type if either operand is a float.

### **Program 116**
Create a function that takes a list of numbers between 1 and 10 (excluding onenumber) and returns the missing number.

To find the missing number in a list containing numbers between 1 and 10, we can use the fact that the sum of the numbers from 1 to 10 is a constant (55). By subtracting the sum of the numbers in the given list from 55, we can identify the missing number.

Here's a Python function that implements this logic:

```python
def find_missing_number(numbers):
    # Total sum of numbers from 1 to 10
    total_sum = sum(range(1, 11))  # This is equivalent to 55
    # Sum of the numbers provided in the list
    given_sum = sum(numbers)
    # The missing number is the difference between the total and given sums
    missing_number = total_sum - given_sum
    return missing_number

# Example usage:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 10]  # 9 is missing
missing = find_missing_number(numbers)
print(f"The missing number is: {missing}")  # Output: The missing number is: 9
```

Explanation:

1. **Total Sum Calculation**:
   - The sum of the numbers from 1 to 10 is calculated using `sum(range(1, 11))`. This gives 55, which is the sum of the first 10 natural numbers.

2. **Given Sum Calculation**:
   - The sum of the numbers in the provided list is calculated using `sum(numbers)`.

3. **Finding the Missing Number**:
   - The missing number is determined by subtracting the sum of the numbers in the list (`given_sum`) from the total sum of numbers from 1 to 10 (`total_sum`).

4. **Example Usage**:
   - In the example, the list `[1, 2, 3, 4, 5, 6, 7, 8, 10]` is missing the number 9. The function correctly identifies and returns 9 as the missing number.

This method works efficiently because it leverages the arithmetic properties of numbers and avoids the need for complex searching or sorting algorithms.

### **Program 118**
Create the function that takes a list of dictionaries and returns the sum of people'sbudgets.

To solve the problem of summing the budgets from a list of dictionaries, where each dictionary represents a person and includes a key for the budget,

## A programmer would typically follow these steps:

1. **Understand the Problem Requirements**

- **Input**: A list of dictionaries, where each dictionary contains at least one key-value pair representing the budget of a person. The key for the budget is consistent across all dictionaries.
- **Output**: The total sum of all the budgets.

2. **Define the Function Signature**

- Define a function that accepts one argument, which will be the list of dictionaries.

```python
def total_budget(people):
    pass
```

3. **Extract and Sum the Budgets**

- Iterate over the list of dictionaries.
- For each dictionary, access the value associated with the budget key.
- Sum these values to get the total budget.

4. **Handle Possible Edge Cases**

- **Empty List**: Ensure that the function handles an empty list without errors.
- **Missing Budget Key**: Decide whether to handle cases where the budget key might be missing in some dictionaries.

5. **Return the Result**

- After calculating the sum, return the result.

6. **Test the Function**

- Test the function with various inputs, including:
  - A list with multiple dictionaries with valid budgets.
  - A list with only one dictionary.
  - An empty list.
  - Lists with varying budget values, including zero.

Sample Implementation

```python
def total_budget(people):
    # Assuming the budget key in each dictionary is 'budget'
    total = 0
    for person in people:
        total += person.get('budget', 0)  # Default to 0 if 'budget' key is missing
    return total
```

Explanation of the Implementation

- **Initialization**: The `total` variable is initialized to 0, which will accumulate the sum of budgets.
- **Iteration**: The function iterates over the list `people`. For each `person` dictionary in the list, it extracts the budget using `person.get('budget', 0)`.
  - The `get` method is used with a default value of `0` to handle cases where the dictionary might not have a `'budget'` key, preventing potential errors.
- **Summation**: The extracted budget values are summed up.
- **Return**: The total budget is returned.

Testing the Function

To ensure the function works correctly, the programmer would run several tests:

```python
# Test cases
people = [
    {'name': 'Alice', 'budget': 1200},
    {'name': 'Bob', 'budget': 1500},
    {'name': 'Charlie', 'budget': 1000}
]

print(total_budget(people))  # Output should be 3700

print(total_budget([]))  # Output should be 0 for an empty list

print(total_budget([{'name': 'Dave', 'budget': 0}, {'name': 'Eve', 'budget': 800}]))  # Output should be 800
```

By following these steps, a programmer can systematically develop and verify the solution.

### **Program 123**
Create a function that takes in two lists and returns True if the second list follows thefirst list by one element, and False otherwise. In other words, determine if the secondlist is the first list shifted to the right by 1.

In [29]:
def simon_says(list1,list2):
# Check if the second list is the first list shifted to the right
   return list1[:-1] == list2[1:]

In [30]:
simon_says([1,2], [5,1])

True

In [31]:
simon_says([1,2], [5,5])

False

 we need to check if the second list is a right-shifted version of the first list by one position. This means that every element in the second list should be the same as the element in the first list that precedes it by one position, and the first element of the second list should be removed

### **Program 125**
An isogram is a word that has no duplicate letters. Create a function that takes astring and returns either True or False depending on whether or not it's an "isogram".

Approach 1:

To determine if a word is an isogram (a word with no duplicate letters), you can create a function that checks for duplicate characters in the given string. Here's a simple approach to solving this problem:

1. **Normalize the Input**: Convert the string to a consistent case (e.g., all lowercase) to ensure that comparisons are case-insensitive.
2. **Check for Duplicates**: Use a set to track the characters you've encountered. If a character appears more than once, it's not an isogram.
3. **Return the Result**: If no duplicates are found, the word is an isogram; otherwise, it isn't.

Here's the implementation of the function:

```python
def is_isogram(word):
    # Convert the word to lowercase to make the function case-insensitive
    word = word.lower()
    # Create an empty set to track unique characters
    seen_characters = set()
    
    # Iterate over each character in the word
    for char in word:
        # Check if the character is already in the set
        # If the letter is already in the set, it's not an isogram
        if char in seen_characters:
            return False
        # Add the character to the set
        # Otherwise, add it to the set
        seen_characters.add(char)
    
    return True

# Example usage:
print(is_isogram("isogram"))  # Output: True
print(is_isogram("isograms")) # Output: False
print(is_isogram("Dermatoglyphics"))  # Output: True
print(is_isogram("aba"))  # Output: False
print(is_isogram("moOse"))  # Output: False (Case insensitive)
```

Explanation:

1. **Normalization**:
   - The function first converts the input `word` to lowercase to ensure that the function is case-insensitive. This means 'A' and 'a' are considered the same letter.

2. **Set for Tracking**:
   - A set named `seen_characters` is used to store each unique character encountered in the word. Sets are ideal for this purpose because they automatically handle duplicates and provide efficient lookup times.

3. **Iteration and Check**:
   - The function iterates over each character in the word. If a character is already in `seen_characters`, the function returns `False`, indicating that the word is not an isogram.
   - If the character is not in the set, it is added to the set.

4. **Returning the Result**:
   - If the loop completes without finding any duplicates, the function returns `True`, indicating that the word is an isogram.

This method efficiently checks for duplicates and ensures that the function works regardless of the letter case.


-----------

Approach 2: How about i sort it and check if there are two instances of the same letter?

Sorting the string and then checking for consecutive duplicate characters is another effective way to determine if a word is an isogram. This method involves the following steps:

1. **Normalize the Input**: Convert the string to a consistent case (e.g., all lowercase) to ensure that comparisons are case-insensitive.
2. **Sort the Characters**: Sort the characters in the string. This brings any duplicate characters next to each other.
3. **Check for Consecutive Duplicates**: Iterate through the sorted characters and check if any two consecutive characters are the same.
4. **Return the Result**: If no consecutive duplicates are found, the word is an isogram; otherwise, it isn't.

Here's how you can implement this approach:

```python
def is_isogram(word):
    # Convert the word to lowercase to ensure the function is case-insensitive
    word = word.lower()
    # Sort the characters of the word
    sorted_word = sorted(word)
    
    # Check for consecutive duplicate characters
    for i in range(1, len(sorted_word)):
        if sorted_word[i] == sorted_word[i - 1]:
            return False
    
    return True

# Example usage:
print(is_isogram("isogram"))  # Output: True
print(is_isogram("isograms")) # Output: False
print(is_isogram("Dermatoglyphics"))  # Output: True
print(is_isogram("aba"))  # Output: False
print(is_isogram("moOse"))  # Output: False (Case insensitive)
```

Explanation:

1. **Normalization**:
   - The function converts the input `word` to lowercase, ensuring the check is case-insensitive.

2. **Sorting**:
   - The sorted function returns a list of characters sorted in alphabetical order. Sorting makes it easy to check for duplicates since any duplicates will be adjacent.

3. **Check for Duplicates**:
   - The function iterates through the sorted list, starting from the second character (index 1) and checks if the current character is the same as the previous one. If any such pair is found, the function returns `False`.

4. **Return the Result**:
   - If the loop completes without finding any duplicates, the function returns `True`, indicating that the word is an isogram.

This approach is simple and effective, leveraging the sorted order to make duplicate detection straightforward. However, it's worth noting that sorting has a time complexity of O(n log n), where n is the number of characters in the string, which is generally more computationally expensive than using a set with O(n) complexity. Nonetheless, for relatively small inputs (as is common with words), this difference is negligible.

-----------

Approach 3: How about I count the occurance of each word and check if there are multiples?

Counting the occurrences of each character in the string and checking if any character appears more than once is another effective method to determine if a word is an isogram. This approach involves using a dictionary or a `collections.Counter` to count the frequency of each character.

Here’s how you can implement this method:

1. **Normalize the Input**: Convert the string to a consistent case to ensure case-insensitive comparison.
2. **Count Character Occurrences**: Use a dictionary or `collections.Counter` to count the occurrences of each character.
3. **Check for Multiples**: Iterate through the counts and check if any character appears more than once.
4. **Return the Result**: If no character appears more than once, the word is an isogram; otherwise, it isn't.

Here is an implementation using `collections.Counter`:

```python
from collections import Counter

def is_isogram(word):
    # Convert the word to lowercase to ensure the function is case-insensitive
    word = word.lower()
    # Count occurrences of each character
    char_count = Counter(word)
    
    # Check if any character count is greater than 1
    for count in char_count.values():
        if count > 1:
            return False
    
    return True

# Example usage:
print(is_isogram("isogram"))  # Output: True
print(is_isogram("isograms")) # Output: False
print(is_isogram("Dermatoglyphics"))  # Output: True
print(is_isogram("aba"))  # Output: False
print(is_isogram("moOse"))  # Output: False (Case insensitive)
```

Explanation:

1. **Normalization**:
   - The function first converts the input `word` to lowercase, ensuring case-insensitive comparisons.

2. **Counting Occurrences**:
   - The `Counter` from the `collections` module is used to count how many times each character appears in the string. `Counter` creates a dictionary-like object where keys are characters, and values are counts of those characters.

3. **Checking for Multiples**:
   - The function iterates through the counts of each character. If any character appears more than once (`count > 1`), the function returns `False`.

4. **Return the Result**:
   - If no character appears more than once, the function returns `True`, indicating that the word is an isogram.

This method is efficient and clear, especially when using `Counter`, which simplifies counting occurrences. It also has a linear time complexity of O(n), where n is the length of the string, making it efficient for larger inputs.


---------

Discussion: The best method to determine if a word is an isogram depends on factors like simplicity, performance, and the typical size of input data. Let's review the three methods:

1. **Using a Set to Track Seen Characters**
- **Pros**:
  - **Efficiency**: O(n) time complexity, where n is the length of the string.
  - **Simplicity**: Easy to understand and implement.
- **Cons**:
  - **Space Complexity**: Requires additional space proportional to the number of unique characters in the string.

2. **Sorting and Checking Consecutive Characters**
- **Pros**:
  - **Simplicity**: Conceptually straightforward and easy to implement.
  - **Space Efficiency**: Only requires space for the sorted string (which is a standard operation).
- **Cons**:
  - **Performance**: O(n log n) time complexity due to sorting, which is less efficient than the set or counting methods.

3. **Counting Character Occurrences**
- **Pros**:
  - **Efficiency**: O(n) time complexity.
  - **Clear Logic**: Uses counting, which is intuitive for checking duplicates.
- **Cons**:
  - **Space Complexity**: Requires additional space for counting, proportional to the number of unique characters.

Conclusion

For most practical purposes, especially with relatively short strings (like words in natural language), the differences in performance may be negligible. However, if we consider both time and space complexity:

- **The Set Method** is generally the most balanced in terms of performance and simplicity. It's efficient and straightforward, making it a good default choice.
- **The Counting Method** using `collections.Counter` is also efficient and provides clear logic for detecting duplicates. It may use more space than the set method but has the advantage of counting frequencies, which can be useful for additional insights.
- **The Sorting Method** is typically less efficient due to the sorting step. However, it may still be a reasonable choice if the problem's constraints are known to allow it, and the simplicity of checking consecutive duplicates is preferred.

**Best Overall Choice**: The **set method** is usually the best overall due to its efficiency and simplicity, especially for large datasets where sorting might become a bottleneck.


### **Program 126**
Create a function that takes a string and returns True or False, depending on whetherthe characters are in order or not.

To create a function that checks whether the characters in a given string are in alphabetical order, you can follow these steps:

1. **Iterate through the String**: Compare each character with the next one.
2. **Check Order**: If any character is greater than the following one, return `False`.
3. **Return Result**: If the loop completes without finding any characters out of order, return `True`.

Here’s the implementation of this function:

```python
def are_characters_in_order(s):
    # Iterate through the string and compare each character with the next one
    for i in range(len(s) - 1):
        if s[i] > s[i + 1]:
            return False
    return True

# Example usage:
print(are_characters_in_order("abc"))  # Output: True
print(are_characters_in_order("abz"))  # Output: True
print(are_characters_in_order("acb"))  # Output: False
print(are_characters_in_order("hello")) # Output: False
print(are_characters_in_order("xyz"))  # Output: True
```

Explanation:

1. **Iterate through the String**:
   - The loop iterates over the indices of the string from `0` to `len(s) - 2`. This is to ensure that `s[i + 1]` is always a valid index.

2. **Check Order**:
   - The comparison `s[i] > s[i + 1]` checks if the current character is greater than the next one. If this condition is true at any point, the function returns `False`, indicating that the characters are not in order.

3. **Return Result**:
   - If the loop completes without finding any characters out of order, the function returns `True`.

This function works for strings containing only alphabetical characters and can be easily adapted for case-insensitive checks by converting the string to lowercase before the comparison.

----

Approach 2:

```python
def is_in_order(s):
  return s ==''.join(sorted(s))
```  


The function `is_in_order(s)` is a concise way to check if the characters in a given string `s` are in alphabetical order. Here's a breakdown of how it works:

Function Explanation

1. **Sorting the String**:
   - The function uses `sorted(s)` to sort the characters of the string `s`. This function returns a list of the characters sorted in ascending (alphabetical) order.

2. **Joining the Sorted Characters**:
   - `''.join(sorted(s))` joins the sorted list of characters back into a single string. The `''.join(...)` method takes an iterable (in this case, the sorted list of characters) and concatenates them into a single string. The empty string `''` before `join` indicates that there are no additional characters (like spaces or commas) inserted between the characters during the join operation.

3. **Comparison**:
   - The function then compares the original string `s` with the newly created sorted string. If they are equal, it means the characters in `s` were already in alphabetical order, so the function returns `True`. If they are not equal, the characters in `s` were not in order, and the function returns `False`.

Example

Let's consider an example to illustrate:

- **Input**: `"abc"`
  - **Sorted**: `"abc"` (same as input)
  - **Comparison**: `s == ''.join(sorted(s))` becomes `"abc" == "abc"`
  - **Output**: `True` (characters are in order)

- **Input**: `"acb"`
  - **Sorted**: `"abc"` (characters rearranged in order)
  - **Comparison**: `s == ''.join(sorted(s))` becomes `"acb" == "abc"`
  - **Output**: `False` (characters are not in order)

This method is straightforward and takes advantage of Python's built-in `sorted()` function to simplify the process of checking if the characters are in alphabetical order.


### **Program 127**
Create a function that takes a number as an argument and returns True or Falsedepending on whether the number is symmetrical or not. A number is symmetricalwhen it is the same as its reverse.

To determine if a number is symmetrical (i.e., it reads the same forwards and backwards), we can convert the number to a string, reverse the string, and then compare the reversed string to the original string. If they are the same, the number is symmetrical; otherwise, it is not.

Here’s a function to accomplish this:

```python
def is_symmetrical(num):
    # Convert the number to a string
    num_str = str(num)
    # Check if the original string is the same as the reversed string
    return num_str == num_str[::-1]

# Example usage:
print(is_symmetrical(121))   # Output: True (symmetrical)
print(is_symmetrical(12321)) # Output: True (symmetrical)
print(is_symmetrical(123))   # Output: False (not symmetrical)
print(is_symmetrical(1221))  # Output: True (symmetrical)
print(is_symmetrical(10))    # Output: False (not symmetrical)
```

Explanation:

1. **Convert the Number to a String**:
   - The function first converts the number to a string using `str(num)`. This conversion allows us to easily reverse the sequence of digits.

2. **Reverse the String**:
   - The slice notation `num_str[::-1]` reverses the string. The `[::-1]` part means "start from the end towards the first element," effectively reversing the string.

3. **Comparison**:
   - The function then compares the original string `num_str` with the reversed string `num_str[::-1]`. If they are equal, the number is symmetrical, and the function returns `True`. If they are not equal, the function returns `False`.

This method is efficient and straightforward, leveraging string manipulation to check for symmetry. It works for any integer, regardless of the number of digits.

**Program 128**
Given a string of numbers separated by a comma and space, return the product ofthe numbers.

To compute the product of numbers given in a string, where the numbers are separated by commas and spaces, you can follow these steps:

1. **Split the String**: Use the `split()` method to separate the numbers in the string based on the ", " delimiter.
2. **Convert to Integers**: Convert the split string values into integers.
3. **Calculate the Product**: Use a loop or a function like `reduce` from the `functools` module to compute the product of the integers.

Here's a Python function that implements this:

```python
from functools import reduce
import operator

def product_of_numbers(num_string):
    # Split the string into a list of number strings
    num_list = num_string.split(", ")
    # Convert the list of number strings to a list of integers
    num_list = map(int, num_list)
    # Calculate the product of the integers
    product = reduce(operator.mul, num_list, 1)
    return product

# Example usage:
print(product_of_numbers("1, 2, 3, 4"))  # Output: 24
print(product_of_numbers("10, 5, 2"))    # Output: 100
print(product_of_numbers("3, 6, 9"))     # Output: 162
print(product_of_numbers("0, 5, 7"))     # Output: 0
```

Explanation:

1. **Splitting the String**:
   - The `split(", ")` method is used to divide the string `num_string` into a list of substrings, each representing a number. The delimiter `", "` specifies that the split should occur at the comma followed by a space.

2. **Converting to Integers**:
   - The `map(int, num_list)` function is used to apply the `int` conversion to each element in the `num_list`. This converts the list of strings into a list of integers.

3. **Calculating the Product**:
   - The `reduce` function from the `functools` module, combined with `operator.mul`, multiplies the integers together. `reduce` applies the `operator.mul` function cumulatively to the items in `num_list`, from left to right, so as to reduce the list to a single product value. The third argument `1` is the initializer, which ensures that the product is correctly calculated even if the list is empty.

This function efficiently computes the product of numbers from a comma-separated string, handling both positive and negative integers, as well as the special case where the list includes zero.

### **Program 131**
Create a function that returns the mean of all digits.

To create a function that calculates the mean (average) of all digits in a given number, you can follow these steps:

1. **Extract the Digits**: Convert the number to a string to easily iterate through each digit.
2. **Convert Digits to Integers**: Convert each character (digit) back to an integer.
3. **Calculate the Sum and Count**: Sum the integers and count the number of digits.
4. **Compute the Mean**: Divide the sum of the digits by the count of digits to get the mean.

Here’s a Python function that implements this:

```python
def mean_of_digits(number):
    # Convert the number to a string to iterate through each character
    num_str = str(number)
    # Calculate the sum of digits and the count of digits
    total = sum(int(digit) for digit in num_str)
    count = len(num_str)
    # Compute the mean
    mean = total / count
    return mean

# Example usage:
print(mean_of_digits(12345))  # Output: 3.0
print(mean_of_digits(11111))  # Output: 1.0
print(mean_of_digits(24680))  # Output: 4.0
print(mean_of_digits(98765))  # Output: 7.0
```

Explanation:

1. **Converting the Number to a String**:
   - The number is converted to a string with `str(number)`. This allows for easy iteration over each digit.

2. **Summing the Digits**:
   - A generator expression `int(digit) for digit in num_str` converts each character in the string back to an integer. The `sum()` function then computes the total of these integers.

3. **Counting the Digits**:
   - The `len(num_str)` function calculates the number of digits in the number.

4. **Calculating the Mean**:
   - The mean is calculated by dividing the total sum of the digits by the count of digits. This value is returned as the result.

This function handles positive integers. If the input can be a negative number or include decimal points, you may need to adjust the function to handle these cases appropriately (e.g., ignoring the sign or decimal point).

There are alternative approaches to calculate the mean of the digits in a number. Here are a couple of different methods:

Method 1: Using List Comprehension and Sum Function

This method is similar to the one provided earlier but uses a list comprehension instead of a generator expression directly in `sum()`.

```python
def mean_of_digits(number):
    # Convert the number to a string and create a list of digits
    digits = [int(digit) for digit in str(number)]
    # Calculate the mean
    mean = sum(digits) / len(digits)
    return mean
```

Method 2: Iterative Approach

This method manually iterates through each digit, accumulates the sum, and counts the number of digits, without converting the number to a string.

```python
def mean_of_digits(number):
    total = 0
    count = 0
    abs_number = abs(number)  # Handle negative numbers
    
    while abs_number > 0:
        digit = abs_number % 10  # Extract the last digit
        total += digit
        count += 1
        abs_number //= 10  # Remove the last digit
    
    if count == 0:  # In case the input number is 0
        return 0
    
    mean = total / count
    return mean
```

Method 3: Using `math.fsum` for High Precision

This method uses `math.fsum` for precise floating-point summation, which can be beneficial for large numbers or numbers with many digits, although in this context, the difference may be negligible.

```python
import math

def mean_of_digits(number):
    digits = [int(digit) for digit in str(number)]
    mean = math.fsum(digits) / len(digits)
    return mean
```

Explanation of Differences:

- **List Comprehension**: Provides a clear and Pythonic way to generate a list of digits. It's concise and easy to read.
- **Iterative Approach**: Avoids converting the number to a string, directly manipulating the number itself. This is useful if you want to avoid string operations.
- **`math.fsum`**: While similar to using `sum()`, `math.fsum` can provide better precision with floating-point arithmetic, although this is more relevant in other contexts (like handling floating-point numbers).

All these methods are valid and will give the correct result. The choice of method can depend on the specific requirements of the problem, such as the need to handle large numbers, the preference for more explicit iteration, or the desire to avoid string conversion.

### **Program 133**
Create a function that takes a list of numbers and return the number that's unique.

To find the unique number in a list where all other numbers appear at least twice, you can use a few different approaches. One straightforward method is to use a dictionary to count the occurrences of each number and then identify the number that occurs only once.

Here’s a function that implements this method:

```python
def find_unique_number(numbers):
    # Create a dictionary to count occurrences of each number
    counts = {}
    for num in numbers:
        counts[num] = counts.get(num, 0) + 1
    
    # Find and return the number with a count of 1
    for num, count in counts.items():
        if count == 1:
            return num

# Example usage:
print(find_unique_number([1, 2, 2, 3, 3]))  # Output: 1
print(find_unique_number([4, 5, 5, 4, 7, 7, 6]))  # Output: 6
print(find_unique_number([9, 8, 9, 8, 7]))  # Output: 7
```

Explanation:

1. **Counting Occurrences**:
   - A dictionary `counts` is used to store the frequency of each number in the list. The `get(num, 0)` method fetches the current count for `num` or returns `0` if `num` is not yet in the dictionary.

2. **Identifying the Unique Number**:
   - After populating the dictionary, the function iterates over the items in `counts` to find the number whose count is `1`. This number is unique in the list.

Alternative Approach: Using `collections.Counter`

You can also use the `Counter` class from the `collections` module, which is designed for counting hashable objects. Here's how to do it:

```python
from collections import Counter

def find_unique_number(numbers):
    # Use Counter to count occurrences
    counts = Counter(numbers)
    # Find and return the number with a count of 1
    for num, count in counts.items():
        if count == 1:
            return num

# Example usage:
print(find_unique_number([1, 2, 2, 3, 3]))  # Output: 1
print(find_unique_number([4, 5, 5, 4, 7, 7, 6]))  # Output: 6
print(find_unique_number([9, 8, 9, 8, 7]))  # Output: 7
```

Both methods are efficient for this problem and will correctly identify the unique number in the list.

Using a set can be an efficient way to find a unique number in a list when all other numbers appear at least twice. Sets in Python are collections of unique elements, and you can leverage this property to identify the unique number.

Method Using Set and Sum

One efficient approach is based on the mathematical property that the sum of unique elements in a set, when doubled and subtracted from the sum of the list, will yield the unique number. This works because the set will contain each number only once, so summing the set and subtracting it from the sum of the list helps isolate the unique number.

Here's the implementation:

```python
def find_unique_number(numbers):
    # Create a set of unique numbers
    unique_numbers = set(numbers)
    # Calculate the sum of all numbers in the list
    sum_all_numbers = sum(numbers)
    # Calculate the sum of unique numbers
    sum_unique_numbers = sum(unique_numbers)
    # The unique number can be found using the formula:
    # 2 * sum_unique_numbers - sum_all_numbers
    unique_number = 2 * sum_unique_numbers - sum_all_numbers
    return unique_number

# Example usage:
print(find_unique_number([1, 2, 2, 3, 3]))  # Output: 1
print(find_unique_number([4, 5, 5, 4, 7, 7, 6]))  # Output: 6
print(find_unique_number([9, 8, 9, 8, 7]))  # Output: 7
```

Explanation:

1. **Set of Unique Numbers**:
   - `set(numbers)` creates a set containing all unique numbers from the list.

2. **Sum Calculations**:
   - `sum(numbers)` gives the sum of all numbers in the list, counting duplicates.
   - `sum(unique_numbers)` gives the sum of the unique numbers (without duplicates).

3. **Finding the Unique Number**:
   - The formula `2 * sum_unique_numbers - sum_all_numbers` works because `sum_all_numbers` includes each non-unique number twice (since they are duplicated in the list). Subtracting the sum of all numbers from twice the sum of the unique numbers isolates the unique number.

Efficiency:

- **Time Complexity**: This method runs in O(n) time, where n is the number of elements in the list. The set creation, summation, and the arithmetic operations all take linear time.
- **Space Complexity**: The space complexity is O(u), where u is the number of unique elements. This is because the set stores each unique element.

Using a set is efficient in this case and provides a clean solution to find the unique number in the list.

### **Program 134**
Your task is to create a Circle constructor that creates a circle with a radius providedby an argument. The circles constructed must have two getters getArea() (PIr^2) andgetPerimeter() (2PI*r) which give both respective areas and perimeter(circumference).

To create a `Circle` class in Python that encapsulates the properties of a circle, we need to include:

1. A constructor to initialize the circle with a given radius.
2. Getter methods `getArea()` and `getPerimeter()` to calculate and return the area and perimeter (circumference) of the circle, respectively.

Here's the implementation:

```python
import math

class Circle:
    def __init__(self, radius):
        self.radius = radius

    def getArea(self):
        return math.pi * (self.radius ** 2)

    def getPerimeter(self):
        return 2 * math.pi * self.radius

# Example usage:
circle = Circle(5)
print("Area:", circle.getArea())          # Output: Area: 78.53981633974483
print("Perimeter:", circle.getPerimeter())  # Output: Perimeter: 31.41592653589793
```
Explanation:

1. **Importing `math` Module**:
   - The `math` module is imported to use `math.pi` for the value of π (pi).

2. **Circle Class**:
   - `__init__(self, radius)`: This is the constructor method that initializes an instance of the `Circle` class with a specified `radius`.
   - `getArea(self)`: This method calculates the area of the circle using the formula \( \text{Area} = \pi \times r^2 \), where \( r \) is the radius.
   - `getPerimeter(self)`: This method calculates the perimeter (circumference) of the circle using the formula \( \text{Perimeter} = 2 \times \pi \times r \), where \( r \) is the radius.

Usage:

- The `Circle` class is instantiated with a radius. The `getArea()` and `getPerimeter()` methods can be called on this instance to retrieve the circle's area and perimeter.

This class design provides a simple and clean way to encapsulate the properties and behaviors of a circle, allowing users to easily compute the area and perimeter based on the radius.

### **Program 135**
Create a function that takes a list of strings and return a list, sorted from shortest tolongest.

To create a function that sorts a list of strings by their length, from shortest to longest, you can use Python's built-in `sorted()` function or the `sort()` method of lists. Both methods allow you to specify a custom key function that determines the sorting order.

Here’s a function that accomplishes this:

```python
def sort_by_length(strings):
    # Use the sorted function with the key parameter set to the length of each string
    return sorted(strings, key=len)

# Example usage:
strings = ["apple", "kiwi", "banana", "cherry", "blueberry"]
sorted_strings = sort_by_length(strings)
print(sorted_strings)  # Output: ['kiwi', 'apple', 'banana', 'cherry', 'blueberry']
```

Explanation:

1. **`sorted()` Function**:
   - The `sorted()` function returns a new list that is sorted based on the specified key function. It does not modify the original list.
   - The `key` parameter is set to `len`, which is a built-in function that returns the length of a string. This means that `sorted()` will sort the list based on the length of each string.

2. **Result**:
   - The resulting list `sorted_strings` contains the original strings sorted by length from shortest to longest.

Using `sort()` Method

Alternatively, you can use the `sort()` method of the list, which sorts the list in place:

```python
def sort_by_length(strings):
    # Sort the list in place using the sort method
    strings.sort(key=len)
    return strings

# Example usage:
strings = ["apple", "kiwi", "banana", "cherry", "blueberry"]
sort_by_length(strings)
print(strings)  # Output: ['kiwi', 'apple', 'banana', 'cherry', 'blueberry']
```

Considerations:

- **`sorted()` vs `sort()`**: The `sorted()` function returns a new list, preserving the original list, while the `sort()` method modifies the list in place. Use `sorted()` if you want to keep the original list unchanged, and `sort()` if you don't need the original list.
- **Key Function**: The `key` parameter can be any function that takes a single argument and returns a value to use for sorting. In this case, `len` is used because it provides the length of the strings.

### **Program 136**
Create a function that validates whether three given integers form a Pythagoreantriplet. The sum of the squares of the two smallest integers must equal the square ofthe largest number to be validated.

To check if three given integers form a Pythagorean triplet, the sum of the squares of the two smaller integers must equal the square of the largest integer. A Pythagorean triplet consists of three integers \(a\), \(b\), and \(c\) such that \(a^2 + b^2 = c^2\).

Here’s how you can implement this check in a Python function:

```python
def is_pythagorean_triplet(a, b, c):
    # First, sort the integers to ensure the largest is always in c
    a, b, c = sorted([a, b, c])
    # Check if the sum of the squares of the two smallest equals the square of the largest
    return a**2 + b**2 == c**2

# Example usage:
print(is_pythagorean_triplet(3, 4, 5))  # Output: True
print(is_pythagorean_triplet(5, 12, 13))  # Output: True
print(is_pythagorean_triplet(1, 2, 3))  # Output: False
```

Explanation:

1. **Sorting**:
   - The integers `a`, `b`, and `c` are sorted so that `c` is always the largest number. This sorting ensures that we always check the sum of the squares of the two smaller numbers against the square of the largest number.

2. **Pythagorean Triplet Check**:
   - The function checks if the sum of the squares of `a` and `b` is equal to the square of `c`. This condition is true for Pythagorean triplets.

Example:

- For the input `(3, 4, 5)`, the sorted numbers are `(3, 4, 5)`. The check \(3^2 + 4^2 = 9 + 16 = 25\) equals \(5^2 = 25\), so the function returns `True`.
- For the input `(1, 2, 3)`, the sorted numbers are `(1, 2, 3)`. The check \(1^2 + 2^2 = 1 + 4 = 5\) does not equal \(3^2 = 9\), so the function returns `False`.

This function accurately identifies whether three integers can form a right triangle, following the Pythagorean theorem.

### **Program 137**
Create a function that takes three integer arguments (a, b, c) and returns the amountof integers which are of equal value.

To create a function that takes three integer arguments and returns the number of integers that are equal, we need to consider all possible cases of equality among the three integers. The function should return:

1. `3` if all three integers are the same.
2. `2` if exactly two of the integers are the same.
3. `0` if none of the integers are the same.

Here's how you can implement this function:

```python
def count_equal(a, b, c):
    if a == b == c:
        return 3  # All three integers are the same
    elif a == b or b == c or a == c:
        return 2  # Exactly two integers are the same
    else:
        return 0  # All integers are different

# Example usage:
print(count_equal(1, 1, 1))  # Output: 3
print(count_equal(2, 2, 3))  # Output: 2
print(count_equal(4, 5, 6))  # Output: 0
```

Explanation:

1. **All Three Equal (`a == b == c`)**:
   - If all three integers are equal, the function returns `3`.

2. **Exactly Two Equal (`a == b`, `b == c`, `a == c`)**:
   - If exactly two of the integers are equal, the function returns `2`. This is checked by three conditions: `a == b`, `b == c`, and `a == c`. These conditions ensure that two and only two numbers are equal.

3. **None Equal**:
   - If none of the above conditions are met, it means all three integers are different, so the function returns `0`.

This approach covers all the possible scenarios for comparing three integers and determining how many are equal.

### **Program 138**
Write a function that converts a dictionary into a list of keys-values tuples.

To convert a dictionary into a list of key-value tuples, you can use the `items()` method of the dictionary, which returns a view object containing the key-value pairs as tuples. You can then convert this view object into a list.

Here's how you can implement this:

```python
def dict_to_tuples(d):
    # Convert dictionary items to a list of tuples
    return list(d.items())

# Example usage:
example_dict = {'a': 1, 'b': 2, 'c': 3}
result = dict_to_tuples(example_dict)
print(result)  # Output: [('a', 1), ('b', 2), ('c', 3)]
```

Explanation:

1. **`d.items()`**:
   - The `items()` method of a dictionary returns a view object that displays a list of a dictionary's key-value tuple pairs. In Python 3, this view object can be converted into a list.

2. **`list()`**:
   - The `list()` function is used to convert the view object returned by `items()` into an actual list. This list contains tuples where each tuple is a pair `(key, value)` from the dictionary.

Example:

- Given a dictionary `example_dict = {'a': 1, 'b': 2, 'c': 3}`, calling `dict_to_tuples(example_dict)` will output `[('a', 1), ('b', 2), ('c', 3)]`.

This method preserves the order of elements in the dictionary, which is particularly useful if the dictionary is ordered, as in Python 3.7 and later versions, where insertion order is guaranteed to be preserved.

### **Program 139**
Write a function that creates a dictionary with each (key, value) pair being the (lowercase, upper case) versions of a letter, respectively.

To create a dictionary where each key is a lowercase letter and the corresponding value is the uppercase version of that letter, you can use the `string` module in Python, which provides convenient string constants for alphabetic characters.

Here’s how you can implement this function:

```python
import string

def create_letter_case_dict():
    # Use a dictionary comprehension to create the (lowercase, uppercase) pairs
    return {char: char.upper() for char in string.ascii_lowercase}

# Example usage:
letter_case_dict = create_letter_case_dict()
print(letter_case_dict)
```

Explanation:

1. **Importing the `string` Module**:
   - The `string` module is imported to use `string.ascii_lowercase`, which is a string containing all lowercase letters in the English alphabet ('a' to 'z').

2. **Dictionary Comprehension**:
   - The dictionary comprehension `{char: char.upper() for char in string.ascii_lowercase}` iterates over each lowercase letter `char` in `string.ascii_lowercase`.
   - For each `char`, it adds an entry to the dictionary where the key is the lowercase letter and the value is `char.upper()`, which converts the character to its uppercase form.

3. **Output**:
   - The resulting dictionary has lowercase letters as keys and their corresponding uppercase letters as values. For example, the key 'a' has the value 'A', the key 'b' has the value 'B', and so on.

Example Output:
The output of `create_letter_case_dict()` would be:

```python
{'a': 'A', 'b': 'B', 'c': 'C', 'd': 'D', 'e': 'E', 'f': 'F', 'g': 'G', 'h': 'H', 'i': 'I', 'j': 'J', 'k': 'K', 'l': 'L', 'm': 'M', 'n': 'N', 'o': 'O', 'p': 'P', 'q': 'Q', 'r': 'R', 's': 'S', 't': 'T', 'u': 'U', 'v': 'V', 'w': 'W', 'x': 'X', 'y': 'Y', 'z': 'Z'}
```

This function efficiently creates the desired dictionary with a simple and readable approach.

To create a dictionary where each key is a lowercase letter and the corresponding value is its uppercase version, based on a list of lowercase letters, you can follow these steps:

1. Iterate over the given list of lowercase letters.
2. For each letter, create a dictionary entry where the key is the lowercase letter and the value is its uppercase version.

Here's how you can implement this:

```python
def mapping(letters):
    # Create a dictionary with each letter mapped to its uppercase version
    return {letter: letter.upper() for letter in letters}

# Example usage:
print(mapping(["p", "s"]))  # Output: {'p': 'P', 's': 'S'}
print(mapping(["a", "b", "c"]))  # Output: {'a': 'A', 'b': 'B', 'c': 'C'}
```

Explanation:

1. **Dictionary Comprehension**:
   - `{letter: letter.upper() for letter in letters}` is a dictionary comprehension that iterates over each `letter` in the provided `letters` list.
   - For each `letter`, it creates a key-value pair where the key is the lowercase `letter` and the value is `letter.upper()`, which converts the letter to its uppercase form.

2. **Function `mapping`**:
   - The function `mapping` takes a list of lowercase letters and returns a dictionary where each letter is mapped to its uppercase version.

Example Outputs:

- For `mapping(["p", "s"])`, the output is `{'p': 'P', 's': 'S'}`.
- For `mapping(["a", "b", "c"])`, the output is `{'a': 'A', 'b': 'B', 'c': 'C'}`.

This approach is concise and leverages Python's dictionary comprehension to create the desired mapping efficiently.

### **Program 140**
Write a function, that replaces all vowels in a string with a specified vowel.

To create a function that replaces all vowels in a string with a specified vowel, you can follow these steps:

1. Define a list of vowels to check for.
2. Iterate through the string and replace each vowel with the specified vowel.
3. Construct and return the modified string.

Here’s how you can implement this:

```python
def replace_vowels(input_string, replacement_vowel):
    # Define the vowels to be replaced
    vowels = "aeiouAEIOU"
    
    # Replace each vowel in the input_string with the replacement_vowel
    result = ''.join(replacement_vowel if char in vowels else char for char in input_string)
    
    return result

# Example usage:
print(replace_vowels("hello world", "i"))  # Output: "hilli wirld"
print(replace_vowels("This is a test", "o"))  # Output: "Thos os o tost"
```

Explanation:

1. **Vowels Definition**:
   - The string `vowels` contains both lowercase and uppercase vowels (`"aeiouAEIOU"`), ensuring that the function can handle vowels in any case.

2. **String Replacement**:
   - `''.join(replacement_vowel if char in vowels else char for char in input_string)` uses a generator expression to iterate through each character in the `input_string`.
   - For each character, it checks if the character is a vowel (`char in vowels`). If it is, it replaces it with `replacement_vowel`. Otherwise, it keeps the character unchanged.
   - `''.join()` concatenates the modified characters into a new string.

3. **Result**:
   - The resulting string with all vowels replaced is returned.

Example Outputs:

- For `replace_vowels("hello world", "i")`, the vowels 'e' and 'o' are replaced with 'i', resulting in `"hilli wirld"`.
- For `replace_vowels("This is a test", "o")`, the vowels 'i' and 'a' are replaced with 'o', resulting in `"Thos os o tost"`.

This approach ensures that all vowels in the string are replaced with the specified vowel while preserving the non-vowel characters.

**Program 140**
Create a function that takes a string as input and capitalizes a letter if its ASCII codeis even and returns its lower case version if its ASCII code is odd.

To create a function that capitalizes a letter if its ASCII code is even and returns its lowercase version if its ASCII code is odd, you can use the following approach:

1. **Check ASCII Code**: Use Python’s `ord()` function to get the ASCII code of each character.
2. **Apply Transformation**: Based on whether the ASCII code is even or odd, transform the character to uppercase or lowercase.
3. **Build Result String**: Construct the result string with the transformed characters.

Here’s the implementation of the function:

```python
def transform_string(s):
    # Create a new string by transforming each character based on its ASCII code
    result = ''.join(
        char.upper() if ord(char) % 2 == 0 else char.lower()
        for char in s
    )
    return result

# Example usage:
input_string = "Hello World"
transformed_string = transform_string(input_string)
print(transformed_string)  # Output: 'HElLo wOrLd'
```

Explanation:

1. **Transform Each Character**:
   - `ord(char)` returns the ASCII code of `char`.
   - `ord(char) % 2 == 0` checks if the ASCII code is even.
   - `char.upper()` converts the character to uppercase if the ASCII code is even.
   - `char.lower()` converts the character to lowercase if the ASCII code is odd.

2. **Generator Expression**:
   - `''.join(...)` concatenates the transformed characters into a new string.

3. **Function `transform_string`**:
   - The function `transform_string` processes each character in the input string `s` according to the ASCII code criteria and returns the transformed string.

Example Outputs:

- For `transform_string("Hello World")`, the output is `'HElLo wOrLd'`, where characters with even ASCII codes are capitalized and those with odd ASCII codes are converted to lowercase.

This function ensures that each character is correctly transformed based on its ASCII code, producing the desired result.